### ISSUE TITLE
Be able to change the favicon

### ISSUE THREAD

**Issue by tardigrde** [datopian/flowershow#557] opened 2023-08-21 05:42 UTC
**User story:** as a publisher, I want to be able to customize my website UX by being able to change the favicon (https://en.wikipedia.org/wiki/Favicon).

referring to comment: https://github.com/datopian/flowershow/issues/541#issuecomment-1674186332

Thanks in advance!

**Comment by avinashkanaujiya** [comment] 2023-09-03 22:26
```javascript
export default {
    nextSeo: {
        // title: "MyBlog blog post",
        // description: "This is a blog about data management",
        additionalLinkTags: [
            {
              rel: 'icon',
              href: "/images/obsidian-icon.ico",
            },
          ],
      },
     // your other configs
};
``` 

this should be added to `content/config.mjs` file

**Comment by avinashkanaujiya** [comment] 2023-09-03 22:27
let me know if it work...

**Comment by rc-austinoneil** [comment] 2023-09-08 22:27
> let me know if it works...

Not the OP but no luck with the provided code. This is able to pass javascript validation, is there something I'm missing?

```javascript
const config = {
  title: "Testing",
  description: "A personal blog about InfoSec, Networking, and Electronic Projects.",
  author: "Testing",
  authorLogo: "/images/me.png",
  domain: "https://testing.com",
  // navLinks: [{ href: "https://github.com", name: "Github" }],
  navBarTitle: {
      logo: "/images/logo.png" // optional
  },
  nextSeo: {
      additionalLinkTags: [
          {
              rel: 'icon',
              href: "/images/favicon.ico",
          },
      ]
  },
};

export default config;
```

**Comment by tardigrde** [comment] 2023-09-09 10:31
Does not work for me either :/
No warning in deployment or in the browser console. 

If I have `public/assets/images/logo.png` file it should work with this config?

```js
const config = {
 # other config parmas
  nextSeo: {
      additionalLinkTags: [
          {
            rel: 'icon',
            href: "/assets/images/logo.png",
          },
      ],
  },
};
```

**Comment by avinashkanaujiya** [comment] 2023-09-11 11:35
Did you check, what is visible in the inspector, in meta section. See if link is getting registered properly in the meta tags. 
Also try removing the cache.

**Comment by olayway** [comment] 2023-09-19 13:59
@tardigrde, @avinashkanaujiya, @delversclub, @rc-austinoneil

I can confirm the favicon is not customizable atm. Thank you for flagging your interest in this feature! I'll do my best to include this in the next version.

**Comment by olayway** [comment] 2023-09-19 15:29
Closing as duplicate of #277

**Closed by olayway** 2023-09-19 15:29 UTC
Labels: Stream: App, customization
