### ISSUE TITLE
 Cannot find tsconfig file "undefined/tsconfig.mdx.json"

### ISSUE THREAD

**Issue by RoarG** [datopian/flowershow#479] opened 2023-04-09 19:05 UTC
**Describe the bug**
 Cannot find tsconfig file "undefined/tsconfig.mdx.json"

**To Reproduce**
1. Follow tutorial: https://flowershow.app/blog/2023-02-16-nextjs-tutorial
2. Follow to step (https://flowershow.app/blog/2023-02-16-nextjs-tutorial#basic-configuration)
3. npm run dev

**Expected behavior**
build and run 

**Error**

```
Warning: Contentlayer might not work as expected on Windows
✘ [ERROR] Cannot find tsconfig file "undefined/tsconfig.mdx.json"

Error: Found 1 problems in 1 documents.

 └── Encountered unexpected errors while processing of 1 documents. This is possibly a bug in Contentlayer. Please open an issue.

     • "Index.md": UnexpectedMDXError: Error: Build failed with 1 error:
     error: Cannot find tsconfig file "undefined/tsconfig.mdx.json"
```

**Desktop (please complete the following information):**
 - OS: Windows 11 22621.1414
 - Browser N/A

**Additional context**
Also I needed to rename the content/config.js to content/config.mjs

**Comment by mohamedsalem401** [comment] 2023-12-27 17:20
Duplicate https://github.com/datopian/flowershow/issues/457

**Comment by rufuspollock** [comment] 2023-12-27 17:35
@mohamedsalem401 great catch. Please then close this by ...

- Adding comment `DUPLICATE. Duplicate of #457` and select close not planned when closing
- add the label duplicate

<img width="876" alt="image" src="https://github.com/datopian/flowershow/assets/180658/fd4ca768-f693-4d93-ba9d-32e2cf5d62bb">

PS: bonus for adding this extra example to https://www.datopian.com/playbook/issues-tasks

**Closed** 2024-01-01 19:13 UTC
Labels: bug, duplicate

**Comment by rufuspollock** [comment] 2024-01-03 18:33
@mohamedsalem401 where is the closing comment i requested 😉

**Comment by mohamedsalem401** [comment] 2024-01-03 20:45
@rufuspollock 
> @mohamedsalem401 where is the closing comment i requested 😉

But I have updated the original comment 😅

> DUPLICATE. Duplicate of #457

**Comment by mohamedsalem401** [comment] 2024-01-03 20:46
DUPLICATE. Duplicate of https://github.com/datopian/flowershow/issues/457
