### ISSUE TITLE
Issues rendering on widescreen

### ISSUE THREAD

**Issue by davidgasquez** [datopian/flowershow#580] opened 2023-10-20 09:27 UTC
The text looks oddly off when opening some of the static pages in the main site like https://flowershow.app/about in a widescreen (3440x1440).

![image](https://github.com/datopian/flowershow/assets/1682202/324f9797-83b5-4a85-a709-72f3c0846472)

**Comment by rufuspollock** [comment] 2023-10-23 16:00
Good point - something must be off in the css.

**Comment by rufuspollock** [comment] 2023-10-23 16:05
BTW just noticed - this may be a duplicate of #566 which i suspect is fixed (and just not pulled downstream yet)

**Comment by rufuspollock** [comment] 2023-10-26 11:22
DUPLICATE #566

**Closed by rufuspollock** 2023-10-26 11:22 UTC
Labels: duplicate, good first issue

**Comment by davidgasquez** [comment] 2023-10-27 09:03
I don't think it's an exact duplicate as the [page I'm having issues rendering](https://flowershow.app/about) thing doesn't have any `table` elements.

I don't think I know enough Tailwind / CSS to fix this in a short time but let me spend some time tinkering and see if I can spot the issue.

**Comment by davidgasquez** [comment] 2023-10-27 09:19
I think the issue is with the `article` element. I can't find it on the source code though! :see_no_evil: Probably because is generated. Don't know where if that's the case! 

![screenshot-2023-10-27_11:13:13](https://github.com/datopian/flowershow/assets/1682202/00d50715-67b7-4a9a-895b-9f94ff817950)
